--- #YAML:1.0
name:               DateTimeX-Subspan-Weekly
version:            0.05
abstract:           Determine whether event falls within weekly recurring range
author:
    - James E Keenan (jkeenan@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    DateTime:        0
    DateTime::Set:   0
    DateTime::Span:  0
    Test::Simple:    0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
